using System;
using System.Collections.Generic;
using System.Globalization;
using Godot;

namespace BipIsland.Drawing;

/// <summary>
/// Stand-in pictures until the hand-drawn art arrives (a port of the Swift app's EmojiPictures).
/// Every word the game can show needs a picture a pre-reader can recognise. These emoji are drawn
/// with the bundled Noto Color Emoji font (via <see cref="Fonts"/>), so they look the same on Mac and
/// Windows. Sentence pictures use two or three emoji in a row, and lifecycles read left to right.
/// When the real art for an id lands in <see cref="PictureNode"/>, delete its row here.
/// </summary>
public static class EmojiPictures
{
    /// <summary>Picture id (pic_duck) to emoji.</summary>
    public static readonly IReadOnlyDictionary<string, string> Icons = new Dictionary<string, string>
    {
        ["pic_bag"] = "👜",
        ["pic_ball"] = "⚽",
        ["pic_banana"] = "🍌",
        ["pic_bat"] = "🦇",
        ["pic_bed"] = "🛏️",
        ["pic_bee"] = "🐝",
        ["pic_bell"] = "🔔",
        ["pic_bike"] = "🚲",
        ["pic_bin"] = "🗑️",
        ["pic_bird"] = "🐦",
        ["pic_biscuit"] = "🍪",
        ["pic_boat"] = "⛵",
        ["pic_bone"] = "🦴",
        ["pic_book"] = "📖",
        ["pic_bowl"] = "🥣",
        ["pic_box"] = "📦",
        ["pic_bug"] = "🐛",
        ["pic_bun"] = "🍞",
        ["pic_bus"] = "🚌",
        ["pic_buzz"] = "🐝",
        ["pic_cake"] = "🍰",
        ["pic_camp"] = "⛺",
        ["pic_can"] = "🥫",
        ["pic_cap"] = "🧢",
        ["pic_car"] = "🚗",
        ["pic_cat"] = "🐱",
        ["pic_chick"] = "🐤",
        ["pic_chin"] = "🧔",
        ["pic_chip"] = "🍟",
        ["pic_cloud"] = "☁️",
        ["pic_coat"] = "🧥",
        ["pic_coin"] = "🪙",
        ["pic_corn"] = "🌽",
        ["pic_cow"] = "🐄",
        ["pic_crab"] = "🦀",
        ["pic_dinner"] = "🍽️",
        ["pic_dish"] = "🍛",
        ["pic_dog"] = "🐶",
        ["pic_doll"] = "🪆",
        ["pic_drum"] = "🥁",
        ["pic_duck"] = "🦆",
        ["pic_egg"] = "🥚",
        ["pic_fan"] = "🪭",
        ["pic_feet"] = "🦶",
        ["pic_fish"] = "🐟",
        ["pic_flag"] = "🚩",
        ["pic_fog"] = "🌫️",
        ["pic_foot"] = "🦶",
        ["pic_fork"] = "🍴",
        ["pic_fox"] = "🦊",
        ["pic_frog"] = "🐸",
        ["pic_girl"] = "👧",
        ["pic_goat"] = "🐐",
        ["pic_hammer"] = "🔨",
        ["pic_hand"] = "✋",
        ["pic_hat"] = "🎩",
        ["pic_hen"] = "🐔",
        ["pic_home"] = "🏠",
        ["pic_hook"] = "🪝",
        ["pic_hut"] = "🛖",
        ["pic_jam"] = "🫙",
        ["pic_jet"] = "✈️",
        ["pic_jug"] = "🏺",
        ["pic_juice"] = "🧃",
        ["pic_kid"] = "🧒",
        ["pic_king"] = "🤴",
        ["pic_kiss"] = "💋",
        ["pic_kite"] = "🪁",
        ["pic_ladder"] = "🪜",
        ["pic_ladybird"] = "🐞",
        ["pic_lamp"] = "💡",
        ["pic_leaf"] = "🍃",
        ["pic_leg"] = "🦵",
        ["pic_letter"] = "✉️",
        ["pic_lip"] = "👄",
        ["pic_log"] = "🪵",
        ["pic_lollipop"] = "🍭",
        ["pic_lunch"] = "🍱",
        ["pic_man"] = "🧑",
        ["pic_map"] = "🗺️",
        ["pic_milk"] = "🥛",
        ["pic_money_c10"] = "🪙",
        ["pic_money_c20"] = "🪙",
        ["pic_money_c50"] = "🪙",
        ["pic_money_r1"] = "🪙",
        ["pic_money_r2"] = "🪙",
        ["pic_money_r5"] = "🪙",
        ["pic_money_r10"] = "💵",
        ["pic_money_r20"] = "💶",
        ["pic_money_r50"] = "💷",
        ["pic_moon"] = "🌙",
        ["pic_mop"] = "🧹",
        ["pic_mouth"] = "😮",
        ["pic_mum"] = "👩",
        ["pic_night"] = "🌃",
        ["pic_nut"] = "🥜",
        ["pic_octopus"] = "🐙",
        ["pic_owl"] = "🦉",
        ["pic_park"] = "🏞️",
        ["pic_paw"] = "🐾",
        ["pic_pen"] = "🖊️",
        ["pic_pencil"] = "✏️",
        ["pic_pie"] = "🥧",
        ["pic_pod"] = "🫛",
        ["pic_pot"] = "🫕",
        ["pic_queen"] = "👸",
        ["pic_rabbit"] = "🐰",
        ["pic_rain"] = "🌧️",
        ["pic_rat"] = "🐀",
        ["pic_ring"] = "💍",
        ["pic_rock"] = "🪨",
        ["pic_rope"] = "🪢",
        ["pic_sandwich"] = "🥪",
        ["pic_saw"] = "🪚",
        ["pic_sea"] = "🌊",
        ["pic_sent_01_a"] = "🐱🟫",
        ["pic_sent_01_b"] = "🐱🎩",
        ["pic_sent_02_a"] = "🐷💇",
        ["pic_sent_02_b"] = "🐷📦",
        ["pic_sent_03_a"] = "🦆🎩",
        ["pic_sent_03_b"] = "🦆🧦",
        ["pic_sent_04_a"] = "🦊📦",
        ["pic_sent_04_b"] = "📦🦊",
        ["pic_sent_05_a"] = "🐸🪵",
        ["pic_sent_05_b"] = "🐸🐶",
        ["pic_sent_06_a"] = "🐟🐟🐟🐟🐟🐟🥘",
        ["pic_sent_06_b"] = "🐟🐟🐟🐟🐟🐟☕",
        ["pic_sent_07_a"] = "🐐⛵",
        ["pic_sent_07_b"] = "🐐🚌",
        ["pic_sent_08_a"] = "🐔🐤🐤🐤🐤🐤🐤🐤🐤🐤🐤",
        ["pic_sent_08_b"] = "🐔🦆🦆🦆🦆🦆🦆🦆🦆🦆🦆",
        ["pic_sent_09_a"] = "🐛🍞",
        ["pic_sent_09_b"] = "🍞🐛",
        ["pic_sent_10_a"] = "🐑🌳",
        ["pic_sent_10_b"] = "🌳🐑",
        ["pic_sent_11_a"] = "🐌🚂",
        ["pic_sent_11_b"] = "🐌🌧️",
        ["pic_sent_12_a"] = "🌙🌊",
        ["pic_sent_12_b"] = "🌙☕",
        ["pic_sent_13_a"] = "🐄🚗",
        ["pic_sent_13_b"] = "🐄🚜",
        ["pic_sent_14_a"] = "🤴🍴",
        ["pic_sent_14_b"] = "🤴💍",
        ["pic_sent_15_a"] = "🐍🍰",
        ["pic_sent_15_b"] = "🐍🚲",
        ["pic_sent_16_a"] = "🐦👕",
        ["pic_sent_16_b"] = "🐦🪹",
        ["pic_shed"] = "🏚️",
        ["pic_sheep"] = "🐑",
        ["pic_shell"] = "🐚",
        ["pic_ship"] = "🚢",
        ["pic_shirt"] = "👕",
        ["pic_shop"] = "🏪",
        ["pic_sister"] = "👭",
        ["pic_snail"] = "🐌",
        ["pic_snake"] = "🐍",
        ["pic_snow"] = "❄️",
        ["pic_soap"] = "🧼",
        ["pic_sock"] = "🧦",
        ["pic_spoon"] = "🥄",
        ["pic_star"] = "⭐",
        ["pic_storm"] = "⛈️",
        ["pic_teddy"] = "🧸",
        ["pic_this"] = "👉",
        ["pic_thumb"] = "👍",
        ["pic_town"] = "🏘️",
        ["pic_train"] = "🚂",
        ["pic_tree"] = "🌳",
        ["pic_truck"] = "🚚",
        ["pic_tube"] = "🧻",
        ["pic_turn"] = "↩️",
        ["pic_umbrella"] = "☂️",
        ["pic_van"] = "🚐",
        ["pic_vet"] = "🩺",
        ["pic_web"] = "🕸️",
        ["pic_wig"] = "👱",
        ["pic_wing"] = "🪽",
        ["pic_wood"] = "🪓🪵",
        ["pic_yak"] = "🦬",
        ["pic_zip"] = "🤐",
        ["pic_zoo"] = "🦁🐵",
    };

    public static Node2D? Make(string id)
    {
        if (!Icons.TryGetValue(id, out var icons)) return null;
        // Count what a person sees (a flag or a family is one picture), like Swift's String.count.
        var count = new StringInfo(icons).LengthInTextElements;
        var size = count <= 2 ? 150 : Math.Max(30, 320 / count);
        var holder = new Node2D();
        holder.AddChild(Glyph(icons, size));
        return holder;
    }

    /// <summary>Emoji text centred on (0, 0) at a font size, the same as the Swift app's emoji labels.</summary>
    public static Label Glyph(string text, int size) => Sketch.Label(text, size, Palette.White, Fonts.Emoji);
}
